export {
  CONTRACT_ERRORS,
  CONTRACT_ERRORS_BY_CONTRACT,
  type ContractErrorCode,
  type ContractErrorInfo,
  type ContractErrorName,
  type ContractName,
  getErrorsForContract,
  getContractError,
  isValidErrorCode,
  isValidContractErrorCode,
} from "./generated/contract-errors";

export const LENDING_CONTRACT_ID =
  "CAPTJPAXEURYXEWGDSCCU3SZDYIP3U7KTS7VQM2EYLLK2JKIR4JIVWIH";

export const LENDING_POOL2_CONTRACT_ID =
  "CD3HUT3N6LLUS4XZUWRIIJZUKN2B3UDDMEH2IMK6S3UKAHTZ6VKKBTYQ";

export const ORACLE_CONTRACT_ID =
  "CDJVAFSJTERWPYEZQJGN2N5N4BMXGMG6A2AWQK4C3V36MRYB4PRSNM2S";

export const BACKSTOP_CONTRACT_ID =
  "CCSNXCONDIFZADRJZZRHMRXDGTC6EMI7ZAYAJPJMXSDHBMOPBLBX5XQX";

export const BACKSTOP_POOL2_CONTRACT_ID =
  "CADKADCLXIZTU7Q3WS5M37HUF5BX3WCSTCM2ESN2JCJK5FBBH57FKSAV";
